# docker-compose.yml
version: "3.8"

services:
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: task_management_application
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3306:3306"
